-- Sequence for WLA_USERS
CREATE SEQUENCE WLA_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Sequence for WLA_POSTS
CREATE SEQUENCE WLA_POST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- WLA_USERS Table
CREATE TABLE WLA_USERS (
    ID NUMBER(19) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(200) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_WLA_USERS PRIMARY KEY (ID)
);

-- WLA_POSTS Table
CREATE TABLE WLA_POSTS (
    ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    VIDEO_URL VARCHAR2(500) NOT NULL,
    CONTENT CLOB,
    STATUS VARCHAR2(20) NOT NULL,
    AUTHOR VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_WLA_POSTS PRIMARY KEY (ID)
);

-- Initial User: stk1 / stk1
INSERT INTO WLA_USERS (ID, USERNAME, PASSWORD, ROLE, CREATED_AT, UPDATED_AT)
VALUES (WLA_USER_SEQ.NEXTVAL, 'stk1', '$2a$10$7Z2P.kQf91pA6WvP1nFf9u/Xv/kZ32LpT.y7d2t23GZ81Q1y6Jqae', 'ROLE_USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Sample Youtube Posts
INSERT INTO WLA_POSTS (ID, TITLE, VIDEO_URL, CONTENT, STATUS, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (WLA_POST_SEQ.NEXTVAL, '스프링 부트 3 핵심 기능 마스터하기', 'https://www.youtube.com/watch?v=7X8Il_e6_W4', 'Spring Boot 3의 새로운 기능과 아키텍처 핵심 요약 영상입니다.', 'NEW', 'stk1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO WLA_POSTS (ID, TITLE, VIDEO_URL, CONTENT, STATUS, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (WLA_POST_SEQ.NEXTVAL, 'React 19 새로운 훅과 최적화 기법', 'https://www.youtube.com/watch?v=8pDqJVdNa44', 'React 19에서 추가된 useActionState, useOptimistic 등 주요 변경점 정리.', 'COMPLETED', 'stk1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO WLA_POSTS (ID, TITLE, VIDEO_URL, CONTENT, STATUS, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (WLA_POST_SEQ.NEXTVAL, 'Docker & Kubernetes 기초부터 실전까지', 'https://www.youtube.com/watch?v=Wf2eSG3owoA', '컨테이너 가상화와 쿠버네티스 클러스터 오케스트레이션 개념 강의.', 'NEW', 'stk1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;
