CREATE TABLE WL_ASTRA_USERS (
  USERNAME VARCHAR2(50 CHAR) PRIMARY KEY,
  PASSWORD_HASH VARCHAR2(100 CHAR) NOT NULL
);
CREATE SEQUENCE WL_ASTRA_POST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE WL_ASTRA_POSTS (
  ID NUMBER(19) PRIMARY KEY,
  TITLE VARCHAR2(200 CHAR) NOT NULL,
  VIDEO_URL VARCHAR2(1000 CHAR) NOT NULL,
  VIDEO_ID VARCHAR2(11 CHAR) NOT NULL,
  CONTENT CLOB,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'NEW' NOT NULL,
  AUTHOR VARCHAR2(50 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  VERSION NUMBER(19) DEFAULT 0 NOT NULL,
  CONSTRAINT WL_ASTRA_POST_STATUS_CK CHECK (STATUS IN ('NEW', 'DONE')),
  CONSTRAINT WL_ASTRA_POST_AUTHOR_FK FOREIGN KEY (AUTHOR) REFERENCES WL_ASTRA_USERS(USERNAME)
);
CREATE INDEX WL_ASTRA_POST_CREATED_IDX ON WL_ASTRA_POSTS(CREATED_AT DESC, ID DESC);
